all:
  hosts:
    node1:
      ansible_host: 192.168.1.210
      ip: 192.168.1.210
      access_ip: 192.168.1.210
    node2:
      ansible_host: 192.168.1.211
      ip: 192.168.1.211
      access_ip: 192.168.1.211
    node3:
      ansible_host: 192.168.1.212
      ip: 192.168.1.212
      access_ip: 192.168.1.212
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
